In [2]:
import json
import pandas as pd
import numpy as np

In [3]:
def load_data(file_name):
    lines = open(file_name).readlines()
    users_list = (json.loads(single_line) for single_line in lines)
    return pd.DataFrame(users_list)

In [4]:
df = load_data('data/users.jsonl')
df

,business_address,first_name,gender,haves,id,languages,last_name,primary_company,wants
0,"{'zipcode': '22763', 'country': 'DE', 'city': ...",Clemens,f,[],1,[],Nill,"{'title': 'Data Engineer', 'name': 'Adler Smar...","[APO SNP, ASW, Administration réseau, Agent De..."
1,"{'zipcode': '22113', 'country': 'DE', 'city': ...",Patrick,m,[AMRT],2,[],Wittwer,"{'title': 'Accountant', 'name': 'Steuber Recyc...","[Bodywork, Advanced Materials, Business Recove..."
2,"{'zipcode': '14055', 'country': 'DE', 'city': ...",Hans,f,"[Business Process Integration, Agency Selectio...",3,"[pt, en]",Kurry,"{'title': 'Professor', 'name': 'Tennisverein S...","[Business Requirements, Agile, Account Directo..."
3,"{'zipcode': '10777', 'country': 'DE', 'city': ...",Barbara,m,"[A/R Management, Allergy, Abstract Paintings, ...",4,[en],Nill,"{'title': 'Professor', 'name': 'Mopolis Media ...",[Agriculture]
4,"{'zipcode': '14195', 'country': 'DE', 'city': ...",Frank,m,"[ASPX, APICS, Ceramic Analysis, Department Org...",5,[pt],Schäfer,"{'title': 'Data Scientist', 'name': 'QuadCover...","[AVL, Central Nervous System, Field Technician..."
5,"{'zipcode': '10179', 'country': 'DE', 'city': ...",Matthias,m,"[Accounting Software, Actuarial Consulting, Ae...",6,[],Quassowsky,"{'title': 'Software Engineer', 'name': 'Senats...","[Bodybuilding, Advisory Councils, Business Pro..."
6,"{'zipcode': '10117', 'country': 'DE', 'city': ...",Andreas,f,"[Agricultural Production, Ad Serving, Accounti...",7,"[de, ru]",Kurry,"{'title': 'Data Scientist', 'name': 'RxMx Germ...","[ATRP, Air Purification, Account Optimization,..."
7,"{'zipcode': '10117', 'country': 'DE', 'city': ...",Andreas,f,"[AFLP, Administrative Assistance, Cold Chain, ...",8,"[es, en]",Nill,"{'title': 'Software Engineer', 'name': 'adviqo...",[Acting]
8,"{'zipcode': '01309', 'country': 'DE', 'city': ...",Frank,m,"[Agricultural Engineering, Action Research, Ac...",9,[],Schmitt,"{'title': 'Professor', 'name': 'Vivantes Netzw...","[Agricultural Extension, Commercial Work, ACIS]"
9,"{'zipcode': '13405', 'country': 'DE', 'city': ...",Joachim,m,[],10,[pt],Wittwer,"{'title': 'Accountant', 'name': 'Bräse & Haged...",[Academic Databases]
10,"{'zipcode': '20357', 'country': 'DE', 'city': ...",Joachim,f,"[Cognitive Development, Civil Procedure, ADB A...",11,"[ru, en]",Shindleman,"{'title': 'Manager', 'name': 'Resonance Space'}","[AT commands, Cognitive Interviewing, Aaton, A..."
11,"{'zipcode': '14467', 'country': 'DE', 'city': ...",Daniel,f,"[AVL Boost, Account Origination, Commercial Ve...",12,[ru],Schuck,"{'title': 'Data Scientist', 'name': 'Hydac Sof...","[Central Heating, Advising Clients, AMPL]"
12,"{'zipcode': '80333', 'country': 'DE', 'city': ...",Matthias,f,"[Actuarial Exams, Epigenetics, Bodywork, Centr...",13,[en],Henschel,"{'title': 'Professor', 'name': 'Bucher Propert...","[Air Operations, AMI, Admissions Counseling]"
13,"{'zipcode': '12159', 'country': 'DE', 'city': ...",Clemens,m,[],14,[pt],Schäfer,"{'title': 'Software Engineer', 'name': 'Mediah...","[Commercially driven, AQTESOLV, Acute, Aging R..."
14,"{'zipcode': '40549', 'country': 'DE', 'city': ...",Clemens,m,"[ADL, Commerciality, APC, ASME Y14.5, Cognitiv...",15,"[es, ru]",Bierbaum,"{'title': 'Software Engineer', 'name': 'WISAG ...","[ACH, Business Partner Relations, Aerial Photo..."
15,"{'zipcode': '20097', 'country': 'DE', 'city': ...",Lars,m,"[Department Liaison, Electrification, Episode,...",16,"[en, de]",Schuck,"{'title': 'Manager', 'name': 'Innside by Meliá...",[]
16,"{'zipcode': '20251', 'country': 'DE', 'city': ...",Daniel,m,"[ARM Assembly, Body Sculpting, AHDL, ACMS, Act...",17,"[es, pt]",Burmeister,"{'title': 'Software Engineer', 'name': 'FEELGO...","[Business Process Mapping, AFIS, Cognitive Coa..."
17,"{'zipcode': '10365', 'country': 'DE', 'city': ...",Klaus,m,"[Celtx, Avante, AMR]",18,[ru],Schuck,"{'title': 'Professor', 'name': 'EventOffice'}","[Aircraft, Agile Application Development, Acco..."
18,"{'zipcode': '10115', 'country': 'DE', 'city': ...",Peter,m,"[ATDD, ADB, Activities of Daily Living, Adobe ...",19,[],Schmitt,"{'title': 'Receptionist', 'name': 'www.perform...",[Aircraft Maintenance]
19,"{'zipcode': '10715', 'country': 'DE', 'city': ...",Daniel,f,"[Aid Effectiveness, Account Handlers, Business...",20,[pt],Schuck,"{'title': 'Professor', 'name': 'Dampfbank Wexs...","[ACSS, Advocate Development, Commissioning Eng..."
20,"{'zipcode': '22459', 'country': 'DE', 'city': ...",Heiko,m,"[Autonomous Maintenance, ATMs, Academic Medica...",21,[],Shindleman,"{'title': 'Professor', 'name': 'Starküche e.K.'}",[Cold Chain]
21,"{'zipcode': '10119', 'country': 'DE', 'city': ...",Hans,m,"[Central Asia, Fieldbus, ADM, Agricultural Res...",22,[ru],Kurry,"{'title': 'Accountant', 'name': 'November - Vo...",[]
22,"{'zipcode': '20457', 'country': 'DE', 'city': ...",Patrick,m,"[Department Budgeting, Agenda Development, Adv...",23,[de],Quassowsky,"{'title': 'Data Engineer', 'name': 'CAPITALins...",[Cold Forming]
23,"{'zipcode': '13405', 'country': 'DE', 'city': ...",Peter,m,"[Business Profitability, Acunetix]",24,[es],Scholz,"{'title': 'Professor', 'name': 'Bräse & Hagedo...",[]
24,"{'zipcode': '5020', 'country': 'DE', 'city': '...",Clemens,f,"[Agile Project Management, AGI 32, Commercial ...",25,[en],Scholz,"{'title': 'Software Engineer', 'name': 'Stocks...","[Centrifugation, Commercial Real Estate Analys..."
25,"{'zipcode': '01309', 'country': 'DE', 'city': ...",Joachim,m,"[Agent Recruitment, Epigenomics, AVR Studio 4]",26,[es],Kurry,"{'title': 'Data Scientist', 'name': 'Vivantes ...","[Aikido, Cognitive Radio, Aboriginal Health, C..."
26,"{'zipcode': '12059', 'country': 'DE', 'city': ...",Frank,f,"[Accredited Buyer Rep, AFS, Cold Rooms, All-So...",27,"[es, ru]",Koehler,"{'title': 'Assistant', 'name': 'nfriendly'}",[Agricultural Law]
27,"{'zipcode': '20097', 'country': 'DE', 'city': ...",Peter,f,"[Bodywork, Celtic]",28,[ru],Schuck,"{'title': 'Assistant', 'name': 'Treibstoff HR ...",[Commercial Music]
28,"{'zipcode': '22761', 'country': 'DE', 'city': ...",Clemens,f,"[Cognitive Coaching, ASTM, A&P]",29,"[pt, de]",Kurry,"{'title': 'Data Engineer', 'name': 'Archer Cre...",[Cohabitation Agreements]
29,"{'zipcode': '22337', 'country': 'DE', 'city': ...",Barbara,f,"[African American Studies, Ad Exchanges, Accou...",30,[pt],Henschel,"{'title': 'Software Engineer', 'name': 'petit ...","[Ableton, ASP Baton]"
...,...,...,...,...,...,...,...,...,...
4970,"{'zipcode': '10117', 'country': 'DE', 'city': ...",Joachim,m,"[Administrative, AMSI Property Management, Cen...",4971,[],Burmeister,"{'title': 'Data Scientist', 'name': 'adviqo Gm...","[Allergy Testing, Central Heating]"
4971,"{'zipcode': '10437', 'country': 'DE', 'city': ...",Hans,f,"[ASPX, Department Supervision]",4972,[],Schäfer,"{'title': 'Assistant', 'name': 'roberlin.de'}",[]
4972,"{'zipcode': '71642', 'country': 'DE', 'city': ...",Joachim,m,[Adagio],4973,[en],Haas,"{'title': 'Professor', 'name': 'teamtechnik Di...","[Academic Background, Actuarial Science, ASON,..."
4973,"{'zipcode': '80992', 'country': 'DE', 'city': ...",Lars,m,"[Absorption, AMD64, Actimize, Adview, Agronomy...",4974,[pt],Bierbaum,"{'title': 'Receptionist', 'name': 'FCS AG'}","[Centralization, Civic, Electrification]"
4974,"{'zipcode': '20097', 'country': 'DE', 'city': ...",Heiko,f,"[Allergens, Department Of Health, Aircraft Sys...",4975,[en],Quassowsky,"{'title': 'Receptionist', 'name': 'AdventureRo...","[Avancé, AQL, ACSP, After Dinner Speaking, Abo..."
4975,"{'zipcode': '10623', 'country': 'DE', 'city': ...",Frank,f,"[Activated Carbon, ADL, Air Compressors, Accou...",4976,[ru],Burmeister,"{'title': 'Professor', 'name': 'Handpicked.io'}",[]
4976,"{'zipcode': '10623', 'country': 'DE', 'city': ...",Hans,m,[Civil Rights Litigation],4977,[ru],Shindleman,"{'title': 'Manager', 'name': 'Handpicked.io'}",[]
4977,"{'zipcode': '22763', 'country': 'DE', 'city': ...",Andreas,m,"[Collabnet, Fieldglass]",4978,[],Haas,"{'title': 'Data Scientist', 'name': 'Adler Sma...","[Commericial, Adwords, Advertising Research, A..."
4978,"{'zipcode': '20095', 'country': 'DE', 'city': ...",Barbara,f,[Business Process Design],4979,[],Brackel,"{'title': 'Receptionist', 'name': 'YourLashes ...","[Centralization, AbleCommerce, ATO]"
4979,"{'zipcode': '22113', 'country': 'DE', 'city': ...",Matthias,m,"[Accounts Production, Business Relationship Ma...",4980,"[es, de]",Scholz,"{'title': 'Software Engineer', 'name': 'Steube...","[Boinx, After Effects, ADM, APhA, Epic Games]"
4980,"{'zipcode': '10439', 'country': 'DE', 'city': ...",Alexander,m,[Administration réseau],4981,"[de, pt]",Bierbaum,"{'title': 'Data Engineer', 'name': 'Sea-Watch ...","[Civic, Adventure Education, AES, AWT, AWS CWI]"
4981,"{'zipcode': '20099', 'country': 'DE', 'city': ...",Gernot,f,"[Adage, AMLS, Agronomy]",4982,[de],Carstens,"{'title': 'Professor', 'name': 'EOS Investment...","[Adapter, ADCs, ARINC 429]"
4982,"{'zipcode': '22113', 'country': 'DE', 'city': ...",Heiko,f,"[Cold Rooms, Action Plan Creation]",4983,[],Kurry,"{'title': 'Assistant', 'name': 'Steuber Recycl...","[Cognos ReportNet, ADIC, Acting Training, Affi..."
4983,"{'zipcode': '40549', 'country': 'DE', 'city': ...",Heiko,m,"[API (DEPRECATED), Cemeteries, ASP.NET Core, A...",4984,"[es, de]",Haas,"{'title': 'Professor', 'name': 'WISAG Care Cat...",[Accountable Care]
4984,"{'zipcode': '10119', 'country': 'DE', 'city': ...",Gernot,f,"[Central Asia, AWR, Accounting Management, AV ...",4985,[],Schäfer,"{'title': 'Software Engineer', 'name': 'byrd t...",[AbleCommerce]
4985,"{'zipcode': '10969', 'country': 'DE', 'city': ...",Peter,m,"[ASTM, Agent Development, Agency Services, A2,...",4986,"[es, en]",Nill,"{'title': 'Manager', 'name': 'EXP360 GmbH'}",[]
4986,"{'zipcode': '1150', 'country': 'DE', 'city': '...",Frank,f,[ARCADY],4987,[],Scholz,"{'title': 'Accountant', 'name': 'Ahimsa'}","[Bohemian, ACT!, AEA]"
4987,"{'zipcode': '10365', 'country': 'DE', 'city': ...",Barbara,m,"[Agricultural Extension, Air Source Heat Pumps...",4988,"[es, ru]",Bierbaum,"{'title': 'Software Engineer', 'name': 'Löwenz...","[Agile Testing, Autonomy iManage, Department S..."
4988,"{'zipcode': '13355', 'country': 'DE', 'city': ...",Patrick,f,"[Civil Rights Law, Account Optimization, Aircr...",4989,"[es, pt]",Haas,"{'title': 'Accountant', 'name': 'NIRx Medical ...",[]
4989,"{'zipcode': '20251', 'country': 'DE', 'city': ...",Frank,f,"[Account Directors, A-133, API, A320, Air Sour...",4990,[es],Bierbaum,"{'title': 'Data Scientist', 'name': 'FEELGOOD-...","[Airborne School, AT&T Connect, Cognitive Diso..."
4990,"{'zipcode': '12629', 'country': 'DE', 'city': ...",Patrick,m,"[Autotitrator, Air Compressors]",4991,[],Haas,"{'title': 'Accountant', 'name': 'Veecom One'}",[Aircraft Accident Investigation]
4991,"{'zipcode': '22089', 'country': 'DE', 'city': ...",Matthias,m,"[Alibre, Air Duct Cleaning, Adobe, APV, CentOS...",4992,[],Gerritsen,"{'title': 'Accountant', 'name': 'HOCHTIEF Infr...","[Agtek, Ceramic Analysis]"
4992,"{'zipcode': '10629', 'country': 'DE', 'city': ...",Andreas,f,"[Allegorithmic, Body Image, Avantis, Afghanist...",4993,[],Bierbaum,"{'title': 'Professor', 'name': 'Property Partn...","[Business Process Outsourcing (BPO), Allergy R..."
4993,"{'zipcode': '10707', 'country': 'DE', 'city': ...",Klaus,f,"[Abdominal, ActionScript, APL, APX, Algorithms...",4994,[],Brackel,"{'title': 'Assistant', 'name': 'Bfw Berlin/Bra...",[Business Process]
4994,"{'zipcode': '20097', 'country': 'DE', 'city': ...",Andreas,m,"[APC, Centerpieces, City Management, Agile Met...",4995,[pt],Henschel,"{'title': 'Manager', 'name': 'Treibstoff HR Ch...",[APAC]
4995,"{'zipcode': '22143', 'country': 'DE', 'city': ...",Hans,f,"[ACT CRM, A1 Assessor, Accountability, Civil S...",4996,[en],Carstens,"{'title': 'Data Engineer', 'name': 'Fördervere...","[Air Conditioning, ADP ezLaborManager]"
4996,"{'zipcode': '71642', 'country': 'DE', 'city': ...",Barbara,f,[],4997,"[en, pt]",Gerritsen,"{'title': 'Receptionist', 'name': 'teamtechnik...","[Body Image, Adobe Certified]"
4997,"{'zipcode': '10437', 'country': 'DE', 'city': ...",Patrick,m,"[Business Process, Figurative Art, Aerial Phot...",4998,[ru],Schäfer,"{'title': 'Software Engineer', 'name': 'roberl...","[Cityscape, Agility, Accelerated Reader, AWIPS]"
4998,"{'zipcode': '22111', 'country': 'DE', 'city': ...",Hans,m,"[Department Supervision, Aaton, Adventure Trav...",4999,[es],Bierbaum,"{'title': 'Data Engineer', 'name': 'Edeka Band...","[Electro-Mechanical Design, APL, A-frames]"
4999,"{'zipcode': '21029', 'country': 'DE', 'city': ...",Andreas,m,"[AMFPHP, ATR, Acronis True Image, Commercial P...",5000,[pt],Carstens,"{'title': 'Software Engineer', 'name': 'Fraunh...","[Adverse Events, African Markets, CentOS 7]"

In [5]:
df['business_address'][0]

{'city': 'Hamburg',
 'country': 'DE',
 'street': 'Griegstraße 75 /22a',
 'zipcode': '22763'}

In [6]:
countries = []

for i in df.index:
    country = df['business_address'][i]['country']
    countries.append(country)
    
df['company_country'] = countries

In [7]:
streets = []
for i in df.index:
    street = df['business_address'][i]['street']
    streets.append(street)
    
df['company_street'] = streets

In [8]:
cities = []
for i in df.index:
    city = df['business_address'][i]['city']
    cities.append(city)
    
df['company_city'] = cities

In [9]:
zip_codes = []
for i in df.index:
    code = df['business_address'][i]['zipcode']
    
    zip_codes.append(code)
    
df['company_zipcode'] = zip_codes

In [10]:
df['full_name'] = df['first_name'] + ' ' +  df['last_name']

In [11]:
df['primary_company'][0]

{'name': 'Adler Smart Solutions', 'title': 'Data Engineer'}

In [12]:
titles = []
for i in df.index:
    job_title = df['primary_company'][i]['title']
    titles.append(job_title)
    
df['job_title'] = titles

In [13]:
companies = []
for i in df.index:
    company = df['primary_company'][i]['name']
    companies.append(company)
    
df['Company'] = companies

In [14]:
numeric_gender = {"m": 0, "f": 1}
df['gender'] = df['gender'].map(numeric_gender)

In [15]:
df = df.drop(['id'], axis=1)

In [16]:
haves_set = set()

for haves_list in df['haves']:
    for have in haves_list:
        haves_set.add(have)

In [17]:
"""
Further Todo's:
transform "haves" feature -> Problem: a lot of unique values. Maybe we need to group them into categories.
transform "languages" feature -> Maybe we should create a feature for every language with 0 (doesn't speaks it) or 1 (speaks it) as value.
transform "wants" feature -> Problem: Same as with the "haves" feature.
Visualize the dataset
convert every feature into numeric (only if we want do machine learning with this data)
"""

'\nFurther Todo\'s:\ntransform "haves" feature -> Problem: a lot of unique values. Maybe we need to group them into categories.\ntransform "languages" feature -> Maybe we should create a feature for every language with 0 (doesn\'t speaks it) or 1 (speaks it) as value.\ntransform "wants" feature -> Problem: Same as with the "haves" feature.\nVisualize the dataset\nconvert every feature into numeric (only if we want do machine learning with this data)\n'

In [18]:
# create csv of users
df.to_csv(
    path_or_buf='data/users.csv',
    columns=['first_name', 'last_name', 'gender', 'haves', 'wants', 'languages'],
    sep=';',
    header=False
)

In [19]:
# send csv to hdfs
from hdfs_helpers import put_in_hdfs

put_in_hdfs('/users/test', 'data/users.csv')

data/users.csv 65536
data/users.csv 131072
data/users.csv 196608
data/users.csv 262144
data/users.csv 327680
data/users.csv 393216
data/users.csv 458752
data/users.csv 524288
data/users.csv 589824
data/users.csv 655360
data/users.csv 720896
data/users.csv 786432
data/users.csv 829601
data/users.csv -1

In [21]:
# create/recreate hive table for users
from hive_handler import recreate_users_csv_table

recreate_users_csv_table()

None